### ISSUE TITLE
TS2v2

### ISSUE THREAD

**Issue by Gigabyte918** [F0RIS/MultiOgarBlobPublic#18]
there is no TS2v2 Gamemode in private server but there is in blob.io original server can you please upload the server on this repo Thank you

там нет TS2v2 Gamemode на частном сервере, но есть в исходном сервере blob.io вы можете загрузить сервер на этом репо Спасибо
tam net TS2v2 Gamemode na chastnom servere, no yest' v iskhodnom servere blob.io vy mozhete zagruzit' server na etom repo Spasibo

**Comment by F0RIS** [comment]
I am not willing to share it. Why you need it in Blob Server?

**Comment by Gigabyte918** [comment]
Beacaue i have an abnormal internet and i am tired of playing these gamemodes and its your property i wont ask again thanks for make an app where we can able to play agar.io on mobile and pc too!
