### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Valdex** [F0RIS/MultiOgarBlobPublic#3]
Gigabyte918 зделал комманды для консоли, что очень полезно добавь!
И ещё я в гейммодах по удалял нерабочие гейммоды. Можешь у  меня скопировать папку гейммодс.

**Comment by Valdex** [comment]
Для термукса точнее

**Comment by F0RIS** [comment]
какие команды? отправки сообщения?) это не он делал)

**Comment by Valdex** [comment]
Mass, merge, и так далее

**Comment by Valdex** [comment]
Я то добавлю с свой **_MultiOgarBlob-Unlimited_** , но твой сервер использую я, юкати, и т.д.

**Comment by F0RIS** [comment]
Я их удалил

**Comment by Valdex** [comment]
Ясно

**Comment by Gigabyte918** [comment]
hey what are you taking about me?

**Comment by Valdex** [comment]
@Gigabyte918 no
