### ISSUE TITLE
Why does this keep happening to me?

### ISSUE THREAD

**Issue by Faris90** [F0RIS/MultiOgarBlobPublic#49]
![IMG_1442](https://user-images.githubusercontent.com/24720470/106528549-8b5ac180-64ae-11eb-9a38-1fb6219fac7e.PNG)

**Comment by Faris90** [comment]
Top right

**Comment by F0RIS** [comment]
how to reproduce?

**Comment by Faris90** [comment]
The camera is broken

**Comment by F0RIS** [comment]
write in discord #support
